version: '3.7'

services:
  petclinic-api:
    image: serenitydojo/serenity-petclinic-api
    container_name: petclinic-api

    build:
      context: ./petclinic-api
      dockerfile: Dockerfile
    ports:
      - "9966:9966"

  petclinic-ui:
    image: serenitydojo/serenity-petclinic-ui
    container_name: petclinic-ui
    depends_on:
      - petclinic-api
    build:
      context: ./petclinic-ui
      dockerfile: Dockerfile
    ports:
      - "8080:80"