name: PetClinic Acceptance Tests

on: [push, pull_request]

jobs:

  start_app:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build and launch the PetClinic app
        run: |
          docker-compose build
          docker-compose up -d

#  TODO: Uncomment this section when you have added the petclinic-acceptance-tests module to your project
#
#  acceptance_tests:
#    needs: [start_app]
#
#    runs-on: ubuntu-latest
#
#    steps:
#      - uses: actions/checkout@v2
#      - name: Run the acceptance tests
#        working-directory: petclinic-acceptance-tests
#        run: mvn clean verify

